version: "3.7"
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 4000:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - maria-data:/var/lib/mysql
volumes:
  maria-data:
    driver: local
